name: Node.js CD - ssh

on:
  push:
    tags:        
      - test-*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: "sudo docker run -p 8080:80 -d ghcr.io/revitate/cicd-demo:dev-13"