name: Node.js CD - ssh

on:
  push:
    tags:        
      - test-*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker run -p 8080:80 -d ghcr.io/revitate/cicd-demo:dev-13
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}